Fix Id collision for document ids
When loading a page with an existing document, we could have an ID
collision between the card of the existing document and the card of the
new document due to the increment of the id. Leading to:

FAILED sv/tests/test_evenement_message.py::test_can_see_and_delete_documents_from_draft_message_in_new_tab - playwright._impl._errors.Error: Locator.click: Error: strict mode violation: locator("#document_card_2 .fr-icon-close-circle-line") resolved to 2 elements:
    1) <span aria-hidden="true" class="fr-icon-close-circle-line"></span> aka get_by_role("link").nth(2)
    2) <span aria-hidden="true" class="fr-icon-close-circle-line"></span> aka get_by_role("link").nth(4)